"""add_name_column_to_user_ssh_keys

Revision ID: afbea05a4705
Revises: 162f4b1482d4
Create Date: 2026-01-18 22:45:15.976715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbea05a4705'
down_revision: Union[str, None] = '162f4b1482d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_connections', 'access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('github_connections', 'refresh_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('github_connections_clerk_user_id_key'), 'github_connections', type_='unique')
    op.drop_index(op.f('idx_github_connections_clerk_user_id'), table_name='github_connections')
    op.create_index(op.f('ix_github_connections_clerk_user_id'), 'github_connections', ['clerk_user_id'], unique=True)
    op.add_column('user_ssh_keys', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_ssh_keys', 'name')
    op.drop_index(op.f('ix_github_connections_clerk_user_id'), table_name='github_connections')
    op.create_index(op.f('idx_github_connections_clerk_user_id'), 'github_connections', ['clerk_user_id'], unique=False)
    op.create_unique_constraint(op.f('github_connections_clerk_user_id_key'), 'github_connections', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('github_connections', 'refresh_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('github_connections', 'access_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
