"""add runs table

Revision ID: d911530da9f8
Revises: e27746e5bb86
Create Date: 2026-01-15 01:56:01.365888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d911530da9f8"
down_revision: Union[str, None] = "e27746e5bb86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("clerk_user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("branch", sa.String(), nullable=False),
        sa.Column("config_path", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("data_center", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("gpu_type", sa.String(), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("security", sa.String(), nullable=False),
        sa.Column("cloud_id", sa.String(), nullable=False),
        sa.Column("pod_id", sa.String(), nullable=False),
        sa.Column("is_spot", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_runs_clerk_user_id"), "runs", ["clerk_user_id"], unique=False
    )
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_github_connections_clerk_user_id"), table_name="github_connections"
    )
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_clerk_user_id"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
